Fix -Wmissing-template-arg-list-after-template-kw errors
After upgrading to clang-r547379, this code doesn't build:

external/deqp/external/vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp
external/deqp/external/vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp:1084:72: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
 1084 |             const auto lo = FloatTypeSelector<GenType>::type::template convert(tcu::Float64(interval.lo()));
      |                                                                        ^

Remove the unnecessary `template` keyword.

Bug: b/379133546
Flag: TEST_ONLY
Test: m libdeqp
Ignore-Khronos-First: Warning fixes for android build, will upstream
Change-Id: I3441051972e14a92db87f6c7e7b330ff615354f1